In [2]:
import requests
from bs4 import BeautifulSoup
import pandas

In [3]:
r = requests.get("https://housing.com/in/buy/searches/P3zgy19bgb2xjywqp")
c = r.content

In [4]:
soup = BeautifulSoup(c,"html.parser")

In [5]:
all = soup.find_all("article",{"class":"css-1nr7r9e"})

In [6]:
l = []
for item in all:
    d = {}
    #to skip the featured article
    if item.find("div",{"class":"css-1ibkxbp"}):
        continue
    
    #to print the name and price of the property
    try:
        d["Name"]=item.find("h2",{"class":"css-1t3f68z"}).text
    except:
        d["Name"] = "Project Name not Found"
        
    try:
        d["Address"] = item.find("a",{"class":"css-16drx2b"}).text
    except:
        d["Address"] = "Address not found"
        
    d["Price"] = item.find("div",{"class":"css-18rodr0"}).text
    l.append(d)
df = pandas.DataFrame(l)
df
#df.to_csv("output.csv")

,Name,Address,Price
0,Majestique Signature Towers,"Baner,Pune",₹79.36 L - 94.5 L
1,Supreme Estia Phase III,"Baner,Baner Road,Pune",₹90.0 L - 1.42 Cr
2,Kunal The Canary Phase I,"Balewadi,Pune",₹91.0 L - 1.35 Cr
3,Supreme Estia,"Baner,Baner Road,Pune",₹96.02 L - 2.98 Cr
4,Kasturi The Balmoral Riverside,"Baner,Pune",₹1.27 Cr - 4.0 Cr
5,Kalpataru Jade Residences,"Baner,Pune",₹1.8 Cr
6,Paranjape Blueridge The Groves,"Hinjewadi,Pimpri Chinchwad,Pune",₹46.9 L
7,Project Name not Found,Panchshil Casa 9,₹5.5 Cr
8,Project Name not Found,Kalash Trove,₹2.3 Cr
9,Project Name not Found,Kalpataru Aurum,₹99.0 L
10,Tejraaj Elevia,"Baner,Pune",₹60.0 L - 1.35 Cr
11,Regency Astra Phase I,"Baner,Baner Road,Pune",₹85.0 L - 1.2 Cr
12,Rachana Bella Casa Tower A,"Baner,Sus Road-Pashan,Pune",₹73.0 L - 97.0 L
13,Palaash Oak,"Baner,Pune",₹72.35 L - 78.91 L
14,Yashada Jubilee Hills,"Baner,Baner Road,Pune",₹1.68 Cr - 3.49 Cr
15,VTP Sierra Phase 1,"Baner,Sus Road-Pashan,Pune",₹60.52 L - 1.0 Cr
16,Supreme Estia Phase I,"Baner,Pune",₹89.01 L - 1.36 Cr
17,Kalpataru Aurum,"Baner,Baner Road,Pune",₹99.0 L - 99.5 L
18,Mandarin 33 West Avenue,"Baner,Pune",₹1.65 Cr - 2.0 Cr